openapi: 3.0.0
servers:
  - url: 'https://checkout-test.adyen.com/v1'
info:
  version: '1'
  title: Adyen Checkout Utility Service
  description: |-
    A web service containing utility functions available for merchants integrating with Checkout APIs.
    ## Authentication
    Each request to the Checkout Utility API must be signed with an API key. For this, obtain an API Key from your Customer Area, as described in [How to get the API key](https://docs.adyen.com/developers/user-management/how-to-get-the-api-key). Then set this key to the `X-API-Key` header value, for example:

    ```
    curl
    -H "Content-Type: application/json" \
    -H "X-API-Key: Your_Checkout_API_key" \
    ...
    ```
    Note that when going live, you need to generate a new API Key to access the [live endpoints](https://docs.adyen.com/developers/development-resources/live-endpoints).

    ## Versioning
    Checkout API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: "vXX", where XX is the version number.

    For example:
    ```
    https://checkout-test.adyen.com/v1/originKeys
    ```
  termsOfService: 'https://www.adyen.com/legal/terms-and-conditions'
  contact:
    name: Adyen Support
    url: 'https://support.adyen.com/'
    email: support@adyen.com
x-groups:
  - General
paths:
  /originKeys:
    post:
      summary: Create originKey values for one or more merchant domains.
      description: This operation takes the origin domains and returns a JSON object containing the corresponding origin keys for the domains.
      x-groupName: General
      x-sortIndex: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutUtilityRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutUtilityResponse'
          description: OK - the request has succeeded.
        '400':
          description: Bad Request - a problem reading or understanding the request.
        '401':
          description: Unauthorized - authentication required.
        '403':
          description: Forbidden - insufficient permissions to process the request.
        '422':
          description: Unprocessable Entity - a request validation error.
        '500':
          description: Internal Server Error - the server could not process the request.
components:
  schemas:
    CheckoutUtilityRequest:
      properties:
        originDomains:
          description: 'The list of origin domains, for which origin keys are requested.'
          items:
            type: string
          type: array
      required:
        - originDomains
    CheckoutUtilityResponse:
      properties:
        originKeys:
          description: 'The list of origin keys for all requested domains. For each list item, the key is the domain and the value is the origin key.'
          type: object
