openapi: 3.1.0
info:
  version: '1'
  x-publicVersion: true
  title: 'Negative balance compensation warning

    '
  description: Adyen sends webhooks to inform you about balance accounts whose balance
    has been negative for 20 or more days. If you do not transfer funds to that balance
    account to cover the negative balance before the scheduled compensation date,
    a transfer is made from your liable balance account on that date.
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
tags:
- name: General
- name: Balance account
webhooks:
  balancePlatform.negativeBalanceCompensationWarning.scheduled:
    post:
      tags:
      - General
      summary: Negative balance compensation scheduled
      description: Adyen sends this webhook to inform you about a balance account
        whose balance has been negative for 20 or more days. If you do not transfer
        funds to that balance account to cover the negative balance before the scheduled
        compensation date, a transfer is made from your liable balance account on
        that date.
      operationId: post-balancePlatform.negativeBalanceCompensationWarning.scheduled
      x-sortIndex: 0
      x-methodName: negativeBalanceCompensationScheduled
      security:
      - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              balancePlatform.negativeBalanceCompensationWarning.scheduled:
                $ref: '#/components/examples/post-balancePlatform.negativeBalanceCompensationWarning.scheduled-balancePlatform.negativeBalanceCompensationWarning.scheduled'
            schema:
              $ref: '#/components/schemas/NegativeBalanceCompensationWarningNotificationRequest'
      responses:
        '200':
          description: No Content - webhook events are accepted on the basis of the
            HTTP status code.
components:
  schemas:
    Amount:
      additionalProperties: false
      properties:
        currency:
          description: The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
          maxLength: 3
          minLength: 3
          type: string
        value:
          description: The amount of the transaction, in [minor units](https://docs.adyen.com/development-resources/currency-codes).
          format: int64
          type: integer
      required:
      - value
      - currency
      type: object
    NegativeBalanceCompensationWarningNotificationData:
      additionalProperties: false
      properties:
        accountHolder:
          description: The details of the account holder who owns the balance account
            with a negative balance.
          $ref: '#/components/schemas/ResourceReference'
        amount:
          description: The negative balance amount of the balance account.
          $ref: '#/components/schemas/Amount'
        balancePlatform:
          description: The unique identifier of the balance platform.
          type: string
        creationDate:
          description: The date and time when the event was triggered, in ISO 8601
            extended format. For example, **2020-12-18T10:15:30+01:00**.
          format: date-time
          type: string
        id:
          description: The ID of the resource.
          type: string
        liableBalanceAccountId:
          description: The balance account ID of the account that will be used to
            compensate the balance account whose balance is negative.
          type: string
        negativeBalanceSince:
          description: The date the balance for the account became negative.
          format: date-time
          type: string
        scheduledCompensationAt:
          description: The date when a compensation transfer to the account is scheduled
            to happen.
          format: date-time
          type: string
      type: object
    NegativeBalanceCompensationWarningNotificationRequest:
      additionalProperties: false
      properties:
        data:
          description: Contains event details.
          $ref: '#/components/schemas/NegativeBalanceCompensationWarningNotificationData'
        environment:
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          type: string
        type:
          description: Type of webhook.
          enum:
          - balancePlatform.negativeBalanceCompensationWarning.scheduled
          type: string
      required:
      - environment
      - type
      - data
      type: object
    Resource:
      additionalProperties: false
      properties:
        balancePlatform:
          description: The unique identifier of the balance platform.
          type: string
        creationDate:
          description: The date and time when the event was triggered, in ISO 8601
            extended format. For example, **2020-12-18T10:15:30+01:00**.
          format: date-time
          type: string
        id:
          description: The ID of the resource.
          type: string
      type: object
    ResourceReference:
      additionalProperties: false
      properties:
        description:
          description: The description of the resource.
          type: string
        id:
          description: The unique identifier of the resource.
          type: string
        reference:
          description: The reference for the resource.
          type: string
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
  examples:
    ? post-balancePlatform.negativeBalanceCompensationWarning.scheduled-balancePlatform.negativeBalanceCompensationWarning.scheduled
    : summary: Negative balance compensation scheduled
      description: Example webhook sent as warning when a negative balance compensation
        is scheduled.
      value:
        data:
          balancePlatform: YOUR_BALANCE_PLATFORM
          creationDate: '2024-10-22T00:00:00+02:00'
          id: BA00000000000000000001
          accountHolder:
            description: Description for the account holder.
            reference: YOUR_REFERENCE
            id: AH00000000000000000001
          amount:
            currency: EUR
            value: -145050
          liableBalanceAccountId: BA11111111111111111111
          negativeBalanceSince: '2024-10-19T00:33:13+02:00'
          scheduledCompensationAt: '2024-12-01T01:00:00+01:00'
        environment: test
        type: balancePlatform.negativeBalanceCompensationWarning.scheduled
