openapi: 3.1.0
info:
  version: '1'
  x-publicVersion: true
  title: Forward API webhook
  description: 'The Forward API sends payment requests to third-party services on
    your behalf.


    Adyen uses webhooks to notify you about the result of Forward API requests.'
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
tags:
- name: General
webhooks:
  forwardApi.notification:
    post:
      tags:
      - General
      summary: Forward API request completed
      description: Adyen forwarded a payment request to the third-party service on
        your behalf.
      operationId: post-forwardApi.notification
      x-sortIndex: 0
      x-methodName: forwardApiRequestCompleted
      security:
      - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              recurring-forwardApi.notification:
                $ref: '#/components/examples/post-forwardApi.notification-recurring-forwardApi.notification'
            schema:
              $ref: '#/components/schemas/ForwardApiNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForwardApiNotificationResponse'
          description: OK - the request has succeeded.
components:
  schemas:
    ForwardApiNotificationData:
      additionalProperties: false
      properties:
        amountCurrency:
          description: The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
          type: string
        amountValue:
          description: The amount of the transaction, in [minor units](https://docs.adyen.com/development-resources/currency-codes).
          format: int64
          type: integer
        eventDateTime:
          description: The transaction date and time.
          format: date-time
          type: string
        externalNetworkTxReferenceFound:
          description: Indicates if the `networkTxReferencePaths` matched a reference
            in the third-party response.
          type: boolean
        externalNetworkTxReferenceRequested:
          description: Indicates if a `networkTxReferencePaths` value was provided
            in the request.
          type: boolean
        externalPartyResponseBody:
          description: The raw response body returned by the third-party service.
          type: string
        externalPsp:
          description: The third-party service that processed the payment request.
          type: string
        externalPspTransactionStatus:
          description: The transaction status returned by the third-party service.
          type: string
        externalTransactionLinkIdFound:
          description: Indicates if the `transactionLinkIdPaths` matched a reference
            in the third-party response.
          type: boolean
        externalTransactionLinkIdRequested:
          description: Indicates if a `transactionLinkIdPaths` value was provided
            in the request.
          type: boolean
        merchantAccountCode:
          description: The merchant account that is used to process the payment.
          type: string
        merchantCountryCode:
          description: The country of the merchant account.
          type: string
        merchantReference:
          description: Your reference to uniquely identify the payment.
          type: string
        pspReference:
          description: Adyen's 16-character reference associated with the request.
            This value is globally unique, so you can use it as the reference when
            you communicate with us about this request.
          type: string
        scheme:
          description: The card network used for the transaction. For example, **visa**
            or **mc**.
          type: string
        shopperReference:
          description: Your reference to uniquely identify this shopper, for example
            user ID or account ID.
          type: string
        storedPaymentMethodId:
          description: The unique identifier of the token.
          type: string
      required:
      - pspReference
      - shopperReference
      - storedPaymentMethodId
      - scheme
      - externalPsp
      - merchantReference
      - eventDateTime
      - merchantAccountCode
      - merchantCountryCode
      type: object
    ForwardApiNotificationRequest:
      additionalProperties: false
      properties:
        createdAt:
          description: The date and time when the webhook was created.
          format: date-time
          type: string
        data:
          description: The details of the Forward API request.
          $ref: '#/components/schemas/ForwardApiNotificationData'
        environment:
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          type: string
        type:
          description: The type of notification.
          type: string
        version:
          description: The version of this webhook type.
          type: string
      required:
      - type
      - createdAt
      type: object
    ForwardApiNotificationResponse:
      additionalProperties: false
      properties:
        notificationResponse:
          description: Respond with any **2xx** HTTP status code to [accept the webhook](https://docs.adyen.com/development-resources/webhooks/#accept-webhooks).
          type: string
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
  examples:
    post-forwardApi.notification-recurring-forwardApi.notification:
      summary: Forward Api Request
      value:
        type: forwardApi.notification
        version: '1'
        createdAt: '2023-02-27T16:14:06+01:00'
        environment: test
        data:
          pspReference: QFQTPCQ8HXSKGK82
          shopperReference: YOUR_SHOPPER_REFERENCE
          storedPaymentMethodId: M5N7TQ4TG5PFWR50
          scheme: visa
          externalPsp: adyen
          merchantReference: YOUR_ORDER_REFERENCE
          externalPspTransactionStatus: Authorised
          eventDateTime: '2023-02-27T16:14:06+01:00'
          merchantAccountCode: YOUR_MERCHANT_ACCOUNT
          merchantCountryCode: NL
          amountValue: 100
          amountCurrency: EUR
          externalPartyResponseBody: '{"status": "success"}'
