openapi: 3.1.0
info:
  title: LegalEntityService
  description: OpenAPI spec for LegalEntityService
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
  version: '4'
  x-timestamp: '2025-11-05T12:34:18Z'
tags:
- name: Legal entities
  x-groupIndex: 6
paths:
  /legalEntities/{id}/requestPeriodicReview:
    post:
      tags:
      - Legal entities
      summary: Request periodic data review.
      description: Requests a periodic data review for the legal entity of the user
        specified in the path.
      operationId: post-legalEntities-id-requestPeriodicReview
      parameters:
      - name: id
        in: path
        description: The unique identifier of the legal entity.
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content - the request has been successfully processed, but
            there is no additional content.
          content:
            application/json: {}
      x-methodName: requestPeriodicReview
      x-sortIndex: 1
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    BasicAuth:
      type: http
      scheme: basic
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
